version: '3.8'
services:
  
  db:
    image: mysql:8.0
    container_name: db_capibara
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      ./.env
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql